title: FireflyFolio HUB
description: My Little HUB (In progress)

excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"    
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - compose.yaml
  - Dockerfile
  - LICENSE
  - package.json
  - package-lock.json
  - tailwind.config.js
  - README.md

  